parameters:
#    user_registration.example.class: User\RegistrationBundle\Example

services:
#    user_registration.example:
#        class: %user_registration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
